# Generated by Django 5.1.6 on 2025-02-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('offer_letter', 'Offer Letter'), ('appointment_letter', 'Appointment Letter'), ('nda', 'Non-Disclosure Agreement'), ('cpci', 'CPCI Certification'), ('internship', 'Internship Certification')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('verification_code', models.CharField(max_length=50)),
            ],
        ),
    ]
