# Generated by Django 5.1.6 on 2025-02-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='document',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
    ]
