# Generated by Django 5.1.6 on 2025-03-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_certificate_delete_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='pdf_file',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
