# Generated by Django 5.1.6 on 2025-03-03 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_certificate_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='generated_pdf',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='start_date',
        ),
    ]
