# Generated by Django 5.1.6 on 2025-03-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_certificate_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='generated_pdf',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
